name: Update Portal

on:
  workflow_dispatch:  
  push:
    branches: 
      - master 
    paths: 
      - 'Mixpanel-OpenAPI/**'   

jobs:
  update-portal:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
      name : checkout-repo
      id: checkout-repo     
     
    - name: inplace-import
      run: curl -X PUT --url 'https://www.apimatic.io/api/api-entities/62bed9a2546037b895e0ba10' -H 'content-type:multipart/form-data' -H 'Authorization:X-Auth-Key wcBLEuKMKPb7QNap7Z5KQfQEd0lzJh2n-Vngc9BzLRWhKNKyB3MVRVa9oiJTULAU' -F 'file=@Mixpanel-OpenAPI/Mixpanel-OpenAPI 3.0.json'
      
    - name: publish-portal
      run: curl --location --request PUT 'https://www.apimatic.io/api/api-entities/62bed9a2546037b895e0ba10/portal/publish' -H 'Content-Length:0' -H 'Authorization:X-Auth-Key wcBLEuKMKPb7QNap7Z5KQfQEd0lzJh2n-Vngc9BzLRWhKNKyB3MVRVa9oiJTULAU'
